config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "mackenzie@unicasts.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged
  	has_attached_file :image, styles: { large: "1000x1000>", medium: "762x426#", thumb: "150x150>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/project.rb
class Project < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged
  	has_attached_file :image, styles: { large: "1000x1000>", medium: "762x426#", thumb: "150x150>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
	end

	def new
		@post = Post.new 
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Hellz yearh, Muchiri! Your article was successfully saved!"
		else
			render 'new', notice: "Oh no, Muchiri! I was unable to save your post."
		end
	end

	def show
	end

	def edit
	end

	def update 
		if @post.update post_params
			redirect_to @post, notice: "Hurray! Your article was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end


	private

	def post_params
		params.require(:post).permit(:title, :content, :image, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@projects = Project.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "Nice Muchiri! Your project was successfully saved!"
		else
			render 'new', notice: "Oh no, Muchiri! I was unable to save your project."
		end
	end

	def show

	end

	def edit
	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "Hurray! Your article was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end



	private

	def project_params
		params.require(:project).permit(:title, :description, :link, :image, :slug)
	end

	def find_project
		@project = Project.friendly.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at DESC")
		@projects = Project.all.limit(3).order("created_at DESC")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
        CodeRay.scan(code, language || :text).div
    end
end

def markdown(text)
    coderayified = CodeRayify.new(filter_html: true,  hard_wrap: true)
    options = {
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :autolink => true,
        :strikethrough => true,
        :lax_html_blocks => true,
        :superscript => true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for your message!</h1>
	<p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="contact1">
	<div class="container-contact1">
		<div class="contact1-pic js-tilt" data-tilt>
			<%= image_tag("img-01.png", :alt => "envelope") %>
		</div>

		<%= form_for @contact, :html => {class: 'contact1-form'} do |f| %>
			<div class="wrap-input1 validate-input" data-validate = "Name is required">
				<%= f.text_field :name, required: true, class: 'input1', type: 'text', placeholder: 'Name'  %>
				<span class="shadow-input1"></span>
			</div>

			<br>

			<div class="wrap-input1 validate-input" data-validate = "Name is required">
				<%= f.email_field :email, required: true, class: 'input1', type: 'text', placeholder: 'Email'  %>
				<span class="shadow-input1"></span>
			</div>

			<br>

			<div class="wrap-input1 validate-input" data-validate = "Name is required">
				<%= f.text_area :message, as: :text, class: 'input1', type: 'text', placeholder: 'Message'  %>
				<span class="shadow-input1"></span>
			</div>

			<div class="hidden">
				<%= f.text_field :nickname, hint: 'leave this field blank' %>
			</div>

			<div class="container-contact1-form-btn">
				<%= button_tag( :class => "contact1-form-btn") do %>
					<span>
						SEND MESSAGE
						<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
					</span>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title>Alex Muchiri</title>
	<link href="//fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="I'm so called an engineer, a 'cartoonist' once in a while, I learn everything I can about what interests me and I truly believe hard work beats talent.">
    <meta name="keywords" content="alex muchiri, muchiri alex, web development, app development, micro controllers, community service, ruby on rails, RoR, Alex Muchiri, Lugayo, Juzwa kenya, Engage Jamii Initiatives, TUK, ISACA, CloudFactory, ">
    <meta name="author" content="Alex Muchiri">
    <%= favicon_link_tag 'icon.png' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header id="main_navigation" class="clearfix">
  		<%= link_to "Aléx Muchiri", root_path, class: "logo" %>

		<a href="#" class="menu"><i class="fa fa-bars"></i></a>
		<nav id="main_nav">
			<%= link_to "Articles", posts_path %>
			<%= link_to "Projects", projects_path %>
			<%= link_to "Contact", new_contact_path %>
			<% if user_signed_in? %>
				<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
			<% end %>
		</nav>
	</header>

	<div id="notice_wrapper">
		<% if notice %>
			<p class="notice"><%= notice %></p>
		<% elsif alert %>
			<p class="alert"><%= alert %></p>
		<% end %>
	</div>

    <%= yield %>
	    <!-- Footer -->
	<footer id="main_footer">
		<div class="footer-info">
			<div class="container">
				<div class="col-md-4 info-footer">
					<h3>Contact Information</h3>
						<p><span><i class="fa fa-map-marker" aria-hidden="true"></i></span>Nairobi, Kenya </p>
						<p><span><i class="fa fa-envelope" aria-hidden="true"></i></span><a href="mailto:hey@muchirialex.me?subject=Say%20Hello" target="_blank">hey@muchirialex.me</a> </p>
						<p><span><i class="fa fa-mobile" aria-hidden="true"></i></span>+254711342261</p>
						<p><span><i class="fa fa-globe" aria-hidden="true"></i></span><a href=" ">muchirialex.me</a> </p>
				</div>
				<div class="col-md-4 ws-footer">
					<h2>About</h2>
					<p>Get product updates, launch info, and special deals by signing up for my product newsletter. <br> <a class="video-subscribe-link" href="#">Join <span class="video-subscribe-link-bold">51,000+</span>&nbsp;friends who have already subscribed to my YouTube channel &rarr;</a></p>
				</div>
				<div class="col-md-4 footer-ws">
					<h3>Newsletter</h3>
					<p>Want to hear when I release new stuff?</p>
					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Email" required="">
						<input type="submit" value="Notify Me!">
					</form>
				</div>
			</div>
		</div>
	<!-- copyright -->
	<div class="copyright">
		<div class="copyright-list">
			<ul>
				<li><a href="https://www.facebook.com/muchirialex.me" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="https://twitter.com/alex_muchiri" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="https://github.com/alex-muchiri" target="_blank"><i class="fa fa-github"></i></a></li>
				<li><a href="https://www.instagram.com/muchiri_alex/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
			</ul>
		</div>
		<div class="copyright-info">
			<p>&copy; 2018 Muchiri Alex. All Rights Reserved.</p>
		</div>
	</div>
	<!-- //copyright -->
	</footer>

	<script>
		$(document).ready(function(){
			setTimeout(function() {
				$('#notice_wrapper').fadeOut("slow", function() {
					$this.remove();
				});
			}, 2000 );
		});
	</script>

	<%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

	/**
	*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
	*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
	/*
	var disqus_config = function () {
	this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	};
	*/
	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	s.src = 'https://muchirialex-me.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_message.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	
	<%= f.label :content, "Write your article here" %><br>
	<%= f.text_area :content %>

	<br>
	<br>

	<%= f.file_field :image %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
			<div class="post">
				<%= link_to post do %>
					<%= image_tag post.image.url(:medium) %>
					<h2><%= post.title %></h2>
				<% end %>

				<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
				<hr>
			</div>	
	<% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @post.title %></h1>
		<hr>
		<%= image_tag @post.image.url(:medium) %>
	</header>

	<div id="content">
		<%= markdown @post.content %>
	</div>

	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "Edit Article", edit_post_path(@post) %>
			<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>
		</div>
	<% end %>

	<hr>

	<div id="share_box">
		<p>Share The ToDo List</p>
		<!-- Twitter -->
	    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @muchirialex - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=120, left=300');void(0);"><i class="fa fa-twitter"></i></a>
	    <!-- Facebook -->
	    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=120, left=300');void(0);"><i class="fa fa-facebook"></i></a>
	    <!-- Google Plus -->
	    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=120, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
	</div>

	<hr>

	<%= render 'disqus' %>
	
</div>

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_message.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :description %><br>
	<%= f.text_area :description %>

	<br>
	<br>

	<%= f.label :link %><br>
	<%= f.text_field :link %>

	<br>
	<br>

	<%= f.file_field :image %>

	<br>
	<br>

	<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @projects.each do |project| %>
			<div class="post">
				<%= link_to project do %>
					<%= image_tag project.image.url(:medium) %>
					<h2><%= project.title %></h2>
				<% end %>

				<p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
				<hr>
			</div>	
	<% end %>
</div>

<%= will_paginate @posts %>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @project.title %></h1>
		<hr>
		<%= image_tag @project.image.url(:medium) %>
	</header>

	<div id="content">
		<%= markdown @project.description %>
		
		<div class="project_button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
		</div>
	</div>

	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "Edit Project", edit_project_path(@project) %>
			<%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this project?"} %>
		</div>
	<% end %>
	<hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>About</h2>
		<hr>
		<p>I'm so called an <b>engineer</b>, a <b>'cartoonist'</b> once in a while.</p>
		<p>Unicorn engineer with 4 years experience, plays community sports, 
		and designs cutting-edge software for problem solving.</br><strike>When</strike> <b>I</b> <strike>am writing</strike> <b>code</b>, <strike>I would make sure that it is written</strike> <b>efficiently.</b></p>
		<p>Hard work beats talent when talent fails to work hard.</p>
	</div>

	<div class="col-2 homepage_content">
		<h2>Stuff I've written</h2>
		<hr>
		<% @posts.each do |post| %>
			<h3><a href="#"><%= link_to post.title, post %></a></h3>
			<p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>
		<% end %>
	</div>

	<div class="col-3 homepage_content">
		<h2>Stuff I've Built</h2>
		<hr>
		<% @projects.each do |project| %>
			<h3><a href="#"><%= link_to project.title, project %></a></h3>
			<p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>
		<% end %>
	</div>
</div>

<section class="clearfix tab">
	<div class="wrapper-tab">
		<div class="tab-row">
			<div class="tab-1">
				<h3>Find and Live off your passion</h3>
				<p>If you get good at something, you’ll be in demand. You can then work for a company if you like. I recommend you try doing it on your own unless you need equipment you can’t afford or get an offer you can’t refuse.</p>
			</div>

			<div class="tab-2 js-tilt" data-tilt>
				<%= image_tag("me2.png", :alt => "me") %>
			</div>
		</div>
	</div>
</section>

<section class="clearfix tab">
	<div class="wrapper-tab">
		<div class="tab-row">
			<div class="inverse-tab-1 js-tilt" data-tilt>
				<%= image_tag("illustration-stream.svg", :alt => "illustration-stream") %>
			</div>

			<div class="inverse-tab-2">
				<h3>One man’s magic = another man’s engineering</h3>
				<p>Engineering problems are under-defined, there are many solutions, good, bad and indifferent. The art is to arrive at a good solution. This is a creative activity, involving imagination, intuition and deliberate choice.</p>
			</div>
		</div>
	</div>
</section>

<script>
	$('.js-tilt').tilt({
		scale: 1.1
	})
</script>